06:43:05: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7fd5ac9db0d0>
06:43:05: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7fd5aaac6180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:43:05: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7fd5ac9d7040; closed: 0>
06:43:05: DEBUG [UserDao.py:36] User registred: User [idUser: None - username: 1315490969 - password: 123456 - names: Luis - lastName: Auz]
06:43:05: DEBUG [CursorPool.py:24] Commit running
06:43:05: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7fd5aaac6180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:43:39: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7fe10e0b29a0>
06:43:39: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7fe10c16d180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:43:39: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7fe10e07d040; closed: 0>
06:43:39: ERROR [CursorPool.py:21] Error happened while executing query. We do rollback
06:43:39: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7fe10c16d180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:43:39: ERROR [UserDao.py:28] Error happened while getting all users
06:44:24: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7fd7a2c939a0>
06:44:24: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7fd7a0d4d180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:44:24: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7fd7a2c5e040; closed: 0>
06:44:24: ERROR [CursorPool.py:21] Error happened while executing query. We do rollback
06:44:24: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7fd7a0d4d180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:44:24: ERROR [UserDao.py:28] Error happened while getting all users
06:44:58: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7f461b4819a0>
06:44:58: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f461953b180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:44:58: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f461b44c040; closed: 0>
06:44:58: ERROR [CursorPool.py:21] Error happened while executing query. We do rollback
06:44:58: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f461953b180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:44:58: ERROR [UserDao.py:28] Error happened while getting all users
06:45:44: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7f4c1bdcc9a0>
06:45:44: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f4c19e86180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:45:44: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f4c1bd97040; closed: 0>
06:45:44: ERROR [CursorPool.py:21] Error happened while executing query. We do rollback
06:45:44: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f4c19e86180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:45:44: ERROR [UserDao.py:28] Error happened while getting all users
06:46:41: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7f85931479a0>
06:46:41: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f8591201180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:46:41: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f8593112040; closed: 0>
06:46:41: ERROR [CursorPool.py:21] Error happened while executing query. We do rollback
06:46:41: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f8591201180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:46:41: ERROR [UserDao.py:28] Error happened while getting all users
06:47:28: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7f29049209a0>
06:47:28: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f29029da180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:47:28: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f29048eb040; closed: 0>
06:47:28: ERROR [CursorPool.py:21] Error happened while executing query. We do rollback. Value Exception: __init__() got an unexpected keyword argument 'idUser'
06:47:28: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f29029da180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:47:28: ERROR [UserDao.py:28] Error happened while getting all users
06:48:38: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7fe74c3909a0>
06:48:38: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7fe74a44a180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
06:48:38: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7fe74c35b040; closed: 0>
06:48:38: DEBUG [UserDao.py:24] User [idUser: 1 - username: 1315490969 - password: 123456 - names: Luis - lastName: Auz]
06:48:38: DEBUG [UserDao.py:25] Getting Users Succesfully
06:48:38: DEBUG [CursorPool.py:24] Commit running
06:48:38: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7fe74a44a180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:34:49: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7f1f198c57c0>
10:34:49: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f1f179ba180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:34:49: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f1f198ce040; closed: 0>
10:34:49: ERROR [CursorPool.py:21] Error happened while executing query. We do rollback. Value Exception: relation "places" does not exist
LINE 1: INSERT INTO places(name) VALUES('San José')
                    ^

10:34:49: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f1f179ba180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:34:49: ERROR [PlaceToTravelDao.py:37] Error happened while inserting place: relation "places" does not exist
LINE 1: INSERT INTO places(name) VALUES('San José')
                    ^

10:34:49: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f1f179ba180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:34:49: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f1f198ce040; closed: 0>
10:34:49: ERROR [CursorPool.py:21] Error happened while executing query. We do rollback. Value Exception: relation "places" does not exist
LINE 1: SELECT * FROM places
                      ^

10:34:49: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f1f179ba180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:34:49: ERROR [PlaceToTravelDao.py:26] Error happened while getting all places to travel: relation "places" does not exist
LINE 1: SELECT * FROM places
                      ^

10:36:35: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7ff5efbc37c0>
10:36:35: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7ff5edcb8180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:36:35: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7ff5efbcc040; closed: 0>
10:36:35: DEBUG [PlaceToTravelDao.py:34] Place inserted: San José
10:36:35: DEBUG [CursorPool.py:24] Commit running
10:36:35: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7ff5edcb8180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:36:35: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7ff5edcb8180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:36:35: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7ff5efbcc040; closed: 0>
10:36:35: DEBUG [PlaceToTravelDao.py:23] Getting Users Succesfully
10:36:35: DEBUG [CursorPool.py:24] Commit running
10:36:35: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7ff5edcb8180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:39:33: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7f64d01737c0>
10:39:33: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f64ce267180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:39:33: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f64d017c040; closed: 0>
10:39:33: DEBUG [PlaceToTravelDao.py:23] Getting Users Succesfully
10:39:33: DEBUG [CursorPool.py:24] Commit running
10:39:33: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f64ce267180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:40:02: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7f9dd5f0f7c0>
10:40:02: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f9dd4003180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:40:02: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f9dd5f18040; closed: 0>
10:40:02: DEBUG [PlaceToTravelDao.py:23] Getting Users Succesfully
10:40:02: DEBUG [CursorPool.py:24] Commit running
10:40:02: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f9dd4003180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:40:02: DEBUG [PlaceToTravelDao.py:44] Place: id1 - namePlace: San José
10:46:48: DEBUG [Connection.py:28] Pool getted: <psycopg2.pool.SimpleConnectionPool object at 0x7f0a5a5547f0>
10:46:48: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f0a5c45a040; closed: 0>
10:46:48: DEBUG [PlaceToTravelDao.py:35] Place inserted: Alajuela
10:46:48: DEBUG [CursorPool.py:24] Commit running
10:46:48: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f0a5c45a040; closed: 0>
10:46:48: DEBUG [PlaceToTravelDao.py:35] Place inserted: Heredia
10:46:48: DEBUG [CursorPool.py:24] Commit running
10:46:48: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f0a5c45a040; closed: 0>
10:46:48: DEBUG [PlaceToTravelDao.py:35] Place inserted: Cartago
10:46:48: DEBUG [CursorPool.py:24] Commit running
10:46:48: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f0a5c45a040; closed: 0>
10:46:48: DEBUG [PlaceToTravelDao.py:35] Place inserted: San Carlos
10:46:48: DEBUG [CursorPool.py:24] Commit running
10:46:48: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f0a5c45a040; closed: 0>
10:46:48: DEBUG [PlaceToTravelDao.py:35] Place inserted: Puntarenas
10:46:48: DEBUG [CursorPool.py:24] Commit running
10:46:48: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f0a5c45a040; closed: 0>
10:46:48: DEBUG [PlaceToTravelDao.py:35] Place inserted: Limón
10:46:48: DEBUG [CursorPool.py:24] Commit running
10:46:48: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [Connection.py:39] Connection obtained: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
10:46:48: DEBUG [CursorPool.py:13] Connection and Cursor obtained succesfully: <cursor object at 0x7f0a5c45a040; closed: 0>
10:46:48: DEBUG [PlaceToTravelDao.py:23] Place: id1 - namePlace: San José
10:46:48: DEBUG [PlaceToTravelDao.py:23] Place: id2 - namePlace: Alajuela
10:46:48: DEBUG [PlaceToTravelDao.py:23] Place: id3 - namePlace: Heredia
10:46:48: DEBUG [PlaceToTravelDao.py:23] Place: id4 - namePlace: Cartago
10:46:48: DEBUG [PlaceToTravelDao.py:23] Place: id5 - namePlace: San Carlos
10:46:48: DEBUG [PlaceToTravelDao.py:23] Place: id6 - namePlace: Puntarenas
10:46:48: DEBUG [PlaceToTravelDao.py:23] Place: id7 - namePlace: Limón
10:46:48: DEBUG [PlaceToTravelDao.py:24] Getting Users Succesfully
10:46:48: DEBUG [CursorPool.py:24] Commit running
10:46:48: DEBUG [Connection.py:49] Unlocked Connection: <connection object at 0x7f0a5a547180; dsn: 'user=postgres password=xxx dbname=autobus_agency host=127.0.0.1 port=5432', closed: 0>
